package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.junit.Test;

public class AddGroupTest extends TestBase {
  //private Map<String, Object> vars;
  //JavascriptExecutor js;

  @Test
  public void addGroup() {
    gotoGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("test1", "test2", "test3"));
    submitGroupCreation();
    returnToGroupPage();
  }

}
