package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;

public class DeleteGroupTest extends TestBase {

  @Test
  public void deleteGroup() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
