package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;

public class DeleteGroupTest extends TestBase {

  @Test
  public void deleteGroup() {
    app.getNavigationHelper().gotoGroupPage();
    //driver.findElement(By.cssSelector(".group:nth-child(5)")).click();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
